from enum import StrEnum


class KnowledgeType(StrEnum):
    POLICY = "POLICY"
    REGULATION = "REGULATION"
    CULTURE = "CULTURE"
    SOP = "SOP"
    TUTORIAL = "TUTORIAL"
    FAQ = "FAQ"
    TROUBLESHOOTING = "TROUBLESHOOTING"
    CHECKLIST = "CHECKLIST"
    BEST_PRACTICE = "BEST_PRACTICE"
    TECHNICAL_GUIDE = "TECHNICAL_GUIDE"

